force-app/main/default/objects/Error_Log__c/Error_Log__c.object-meta.xml
<CustomObject>
    <label>Error Log</label>
    <nameField>
        <label>Error Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Error_Log__c/fields/Log_DateTime__c.field-meta.xml
<CustomField>
    <fullName>Log_DateTime__c</fullName>
    <label>Log DateTime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Log_details__c.field-meta.xml
<CustomField>
    <fullName>Log_details__c</fullName>
    <label>Log details</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Process_Name__c.field-meta.xml
<CustomField>
    <fullName>Process_Name__c</fullName>
    <label>Process Name</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ErrorLogHandler.cls
public class ErrorLogHandler {
    
    public static void doHandleException(System.Exception ex , String processName){
        //LogHandler.doHandleException();
        Error_Log__c  transactionLog = new Error_Log__c (
            Log_details__c  = ex.getStackTraceString() +'<br/> <strong> Mesage is </strong> ' + ex.getMessage() 
            + '<br/> ' + ex.getCause() +' <br/> '+ ex.getTypeName()+' <br/> '+ex.getLineNumber(),
            Log_DateTime__c  = System.Now(),
            Process_Name__c    = processName
        );
        
        insert transactionLog;
    }
    
    public static void doHandleException(System.Exception ex , String processName, String errorMessage){
        
        String htmlBody = '';
        if(ex != null){
            htmlBody = ex.getStackTraceString() +'<br/> <strong> Mesage is </strong> ' + ex.getMessage() 
            + '<br/> ' + ex.getCause() +' <br/> '+ ex.getTypeName()+' <br/> '+ex.getLineNumber();
        }
        if(!String.isBlank(errorMessage)){
            htmlBody += errorMessage;
        }
        Error_Log__c  transactionLog = new Error_Log__c (
            Log_details__c  = htmlBody,
            Log_DateTime__c  = System.Now(),
            Process_Name__c    = processName
        );
        
        insert transactionLog;
    }
    
    public static void doHandleExceptionWithError(String errors , String processName){
        
        Error_Log__c  transactionLog = new Error_Log__c (
            Log_details__c  = errors,
            Log_DateTime__c  = System.Now(),
            Process_Name__c    = processName
        );
        
        insert transactionLog;
    }
}